### ISSUE TITLE
Release the latest version

### ISSUE THREAD

**Issue by kenji-miyake** [ComPWA/mirrors-markdown-link-check#2]
## Problem description

Today, [v3.9.1](https://github.com/tcort/markdown-link-check/releases/tag/v3.9.1) has been released.
This resolves the error of multiple inputs. https://github.com/tcort/markdown-link-check/issues/78

## Proposed solution

@redeboer Could you release the latest release, please? :pray:

**Comment by redeboer** [comment]
Hi @kenji-miyake, thanks for notifying! I hadn't noticed that GitHub has deactivated the [upgrade cron job](https://github.com/ComPWA/mirrors-markdown-link-check/actions/workflows/ci.yml) due to inactivity (within 60 days). I've manually run the upgrade job and will reduce the cron job time to avoid this (🤞 ) in the future.

**Comment by kenji-miyake** [comment]
Oh, thank you for your quick reply. :smile:

**Comment by kenji-miyake** [comment]
Released. https://github.com/ComPWA/mirrors-markdown-link-check/releases/tag/v3.9.1

**Comment by redeboer** [comment]
Btw, it seems that the upstream repo has defined a `.pre-commit-hooks.yaml` now: https://github.com/tcort/markdown-link-check/commit/6095b285e39a0b019a49a241e131ae1828d53ca8. Perhaps that makes this mirror redundant?

**Comment by kenji-miyake** [comment]
@redeboer I'm sorry, there was a bug. :pleading_face: 
https://github.com/tcort/markdown-link-check/pull/182

> Btw, it seems that the upstream repo has defined a .pre-commit-hooks.yaml now: tcort/markdown-link-check@6095b28. Perhaps that makes this mirror redundant?

Ah, it might be so, I forgot that.
I think this repository can be archived, but anyway, it was very helpful for me.
Thank you!

**Comment by redeboer** [comment]
> I'm sorry, there was a bug. 🥺

Ok no problem, I'll rerun the upgrade job once a new upstream release is out.

> I think this repository can be archived, but anyway, it was very helpful for me.

Give it a try, switching the repo url of your hook to https://github.com/tcort/markdown-link-check. The pre-commit-hooks config looks different than the one in this mirror though, so if it works, it could be pre-commit just runs a local Node.js version of markdown-link-check if you also installed that (I'm not developing in node, so not sure).

**Comment by kenji-miyake** [comment]
I tested it here and it worked!
https://github.com/autowarefoundation/autoware.universe/pull/283

**Comment by redeboer** [comment]
> I tested it here and it worked!
> [autowarefoundation/autoware.universe#283](https://github.com/autowarefoundation/autoware.universe/pull/283)

Yup, just tried it locally as well, works well. So I'll archive this repo --> https://github.com/ComPWA/mirrors-markdown-link-check/commit/b0fa1e66dcfc02d52d17344da74bfb39342054b0
